services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=prostor
      - POSTGRES_PASSWORD=prostor
      - POSTGRES_DB=prostor
